kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvl
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
     path: "/mnt/data/html/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: v-claim
spec:
  storageClassName: manual
  accessModes:
     - ReadWriteOnce
  resources:
    requests:
     storage: 5Gi
