apiVersion:  v1
kind: Pod
metadata:
  name: new2
  labels:
     app: nginx
spec:
  selector:
   matchLabels:
    app: nginx
  replicas: 4
  template:
   metadata:
     labels:
      app: n1
spec:
  volumes:
        - name: pv-claim
          persistentVolumeClaim:
              claimName: v-claim
  containers:
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80
          volumeMounts: 
            - mountPath: "/usr/share/nginx/html/"
              name: pv-claim






    
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service222
spec:
  selector:
     app: nginx
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 31003
  type: NodePort


